### ISSUE TITLE
Chinese Digital Calipers 150mm mounting documentation error

### ISSUE THREAD

**Issue by rkaronde** [aderusha/DDD-Printable-Wall-Control-System#2]
The current instructions are
Designed for 150mm and 300mm calipers of the sort you'll find from various Chinese vendors. Combine with 2x2 L brackets and a 2x2 spacer.

- Should the spacer be 2x3?
- Should the bracket be 2x1?

Also both the tool holder and the bracket have a slot, how will the tool holder snap in the bracket?

**Comment by aderusha** [comment]
Good catch and thanks for bringing it to my attention! I've updated the documentation on that part to better reflect reality 😃 

One primary goal with my designs is to provide models that can be loaded directly into your slicer and print in the provided orientation without supports.  This can sometimes be challenging due to the geometry required by some models, and the calipers happen to be one of them.  

Instead of printing the tabs on that model, as you've noted you'll find a slot.  What you'll need to do is to print 4x of the [4x10x8mm Pin](https://github.com/aderusha/DDD-Printable-Wall-Control-System/blob/main/Centerpieces/Spacer_blank_flush/4x10x8mm%20Pin.stl) models and press them into the slots to complete the assembled unit.
